import { HugeiconsIcon } from "@hugeicons/react";
import {
  Activity01Icon,
  Alert02Icon,
  Analytics01Icon,
  AnalyticsUpIcon,
  AiSparklesIcon,
  ArrowReloadHorizontalIcon,
  BarChartIcon,
  Call02Icon,
  Camera01Icon,
  Cancel01Icon,
  ChampionIcon,
  ChartDecreaseIcon,
  CheckListIcon,
  CheckmarkCircle01Icon,
  Clock01Icon,
  CodeIcon,
  Coins01Icon,
  Copy01Icon,
  DashboardSquare01Icon,
  Delete02Icon,
  Download01Icon,
  File01Icon,
  FileEditIcon,
  FilterIcon,
  FlashIcon,
  GiftIcon,
  GlobeIcon,
  HelpCircleIcon,
  Image01Icon,
  Invoice01Icon,
  Layout01Icon,
  Money01Icon,
  PackageAddIcon,
  PackageIcon,
  PackageRemoveIcon,
  PencilEdit02Icon,
  PercentSquareIcon,
  PrinterIcon,
  Search01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SleepingIcon,
  SnowIcon,
  SparklesIcon,
  StarIcon,
  Store01Icon,
  Tag01Icon,
  Target02Icon,
  Tick01Icon,
  UserGroupIcon,
  UserIcon,
  ViewIcon,
  WhatsappIcon,
} from "@hugeicons/core-free-icons";

/**
 * Hugeicons, as required by Salla's embedded design guidelines.
 * Components use semantic names so icons can be swapped in one place.
 */
const ICONS = {
  activity: Activity01Icon,
  aiSparkles: AiSparklesIcon,
  alert: Alert02Icon,
  analytics: Analytics01Icon,
  analyticsUp: AnalyticsUpIcon,
  bag: ShoppingBag01Icon,
  call: Call02Icon,
  camera: Camera01Icon,
  barChart: BarChartIcon,
  cart: ShoppingCart01Icon,
  check: Tick01Icon,
  checkCircle: CheckmarkCircle01Icon,
  checklist: CheckListIcon,
  clock: Clock01Icon,
  close: Cancel01Icon,
  code: CodeIcon,
  coins: Coins01Icon,
  copy: Copy01Icon,
  dashboard: DashboardSquare01Icon,
  delete: Delete02Icon,
  download: Download01Icon,
  edit: PencilEdit02Icon,
  file: File01Icon,
  fileEdit: FileEditIcon,
  filter: FilterIcon,
  flash: FlashIcon,
  gift: GiftIcon,
  globe: GlobeIcon,
  help: HelpCircleIcon,
  image: Image01Icon,
  invoice: Invoice01Icon,
  layout: Layout01Icon,
  money: Money01Icon,
  outOfStock: PackageRemoveIcon,
  package: PackageIcon,
  percent: PercentSquareIcon,
  printer: PrinterIcon,
  pulse: Activity01Icon,
  refresh: ArrowReloadHorizontalIcon,
  reload: ArrowReloadHorizontalIcon,
  restock: PackageAddIcon,
  search: Search01Icon,
  shoppingBag: ShoppingBag01Icon,
  sleeping: SleepingIcon,
  snow: SnowIcon,
  sparkles: SparklesIcon,
  star: StarIcon,
  store: Store01Icon,
  tag: Tag01Icon,
  target: Target02Icon,
  tick: Tick01Icon,
  timer: Clock01Icon,
  trash: Delete02Icon,
  trendDown: ChartDecreaseIcon,
  trophy: ChampionIcon,
  user: UserIcon,
  users: UserGroupIcon,
  view: ViewIcon,
  whatsapp: WhatsappIcon,
};

export default function Icon({ name, size = 16, className }) {
  const icon = ICONS[name];
  if (!icon) return null;

  return (
    <HugeiconsIcon
      icon={icon}
      size={size}
      strokeWidth={1.5}
      className={className}
      aria-hidden="true"
      focusable="false"
    />
  );
}
